name: Build SwipeDown27 Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  dpkg-build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install dpkg
      run: |
        brew install dpkg

    - name: Set Permissions
      run: |
        chmod -R 755 control
        chmod 644 control

    - name: Build Deb Package
      run: |
        dpkg-deb -Zxz --root-owner-group -b . com.torxed.swipedown27_1.0.0_iphoneos-arm.deb

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SwipeDown27-Release
        path: "*.deb"
